<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>legend.forkedskylights</RootNamespace>
        <FileVersion>5.28.26</FileVersion>
        <TargetFramework>net481</TargetFramework>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <DebugType>none</DebugType>
        <LangVersion>latest</LangVersion>
        <OutputPath>Assemblies</OutputPath>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Lib.Harmony">
            <ExcludeAssets>runtime</ExcludeAssets>
            <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <Version>2.4.1</Version>
        </PackageReference>

        <PackageReference Include="Krafs.Rimworld.Ref">
            <Version>1.6.4565-beta</Version>
            <ExcludeAssets>runtime</ExcludeAssets>
            <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <Reference Include="Dubs Skylight">
            <HintPath>Dubs Skylight.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>
</Project>
